language: python
python:
- '3.6'
services:
- docker
install:
- pip install docker-compose
script:
- docker-compose build
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
- docker-compose push
env:
  matrix:
    secure: nC2r2/quy/Q3RZixLY0J0IFbt9EmiGcgADnLUsmzDOICFftVKRNEMPCDuu3/KQLxKzoPeSoArJxtgGOtcasa82DyybpfxPHZap6axFw3wVNPRYd//iVnCh8kN/cwYAkppYNuXSzynQwNt21LcfadFzD9xXLI0he/1FWg4ttPuF8sJo3V6I09AcDfjU3hM7Q1Q8F3zl5pvcz0ZWdtLtLGlygQJEuOYkS43KZ2JjfOu9LeHwmX/iHAyLLdudRmHpO2tEDQYQ+q4YT8+rpsSPEv49TnYkFe6nUOi6d6HS216/R7y5gT3PsRJ0iaehB3ONkor7qLGPvaPM4/KMWoshEUMTaxlAeVmIckMkTYyzZZMzCWzN3bPhG4A+kUCjLzNwdRJjmoADPeZvFX6La2k3HvC06iBnGbcm1au17CDJzoxWd3x0vMIV/630vMlojbn+jhfmWZFon+IT/ajmlRKbTjcT4zUUZTBLBSffYIpwx97coXST2BEtonaFSaGw2DNIlfn8oUO7DRtmbwk65rtZh+zjQLs8+KFynF+gcPCoAtyGL7vMEmyOxUAXNIiODFguQFoIs1CAwYmKGqGd361FkDdZ0aJyNpVB5Sih2oZTiq8uhRVjq7/M/MQwGIP2mQlJEIZYJeEgqq1S9i3gHkdk+e/kigyAI7w9RXOz6qudAbUco=
