language: go
go:
- 1.9
services:
- docker
install:
- go get -u github.com/golang/dep/cmd/dep
script:
- dep ensure && go test -v ./... && go install && dockerfiles build && docker login -u="summychoutoto" -p="zhou88270273" && dockerfiles push
