version: "2"

services:
  centos:
    build:
      context: centos/7.3.1611
      dockerfile: Dockerfile
    image: laincloud/centos:7.3.1611

  golang:
    build:
      context: golang/1.8.3
      dockerfile: Dockerfile
    image: laincloud/golang:1.8.3
    depends_on:
      - centos

  java:
    build:
      context: java/8u131
      dockerfile: Dockerfile
    image: laincloud/java:8u131
    depends_on:
      - centos

  maven:
    build:
      context: maven/3.5.0-jdk8u131
      dockerfile: Dockerfile
    image: laincloud/maven:3.5.0-jdk8u131
    depends_on:
      - java

  maven-kotlin:
    build:
      context: maven-kotlin/3.5.0-jdk8u131-1.1.3-2
      dockerfile: Dockerfile
    image: laincloud/maven-kotlin:3.5.0-jdk8u131-1.1.3-2
    depends_on:
      - maven

  tomcat:
    build:
      context: tomcat/8.5.20-jdk8u131
      dockerfile: Dockerfile
    image: laincloud/tomcat:8.5.20-jdk8u131
    depends_on:
      - java
